const hiring = [
    { vacancy: "MNCs", active_hiring: "2.1K+" },
    { vacancy: "Edtech", active_hiring: "156+" },
    { vacancy: "Unicorns", active_hiring: "97+" },
    { vacancy: "Healthcare", active_hiring: "606+" },
    { vacancy: "Internet", active_hiring: "263+" },
    { vacancy: "B2C", active_hiring: "2.4K+" },
    { vacancy: "B2B", active_hiring: "1.8K+" },
    { vacancy: "Fintech", active_hiring: "743+" },
    { vacancy: "AI & ML", active_hiring: "321+" },
    { vacancy: "Cybersecurity", active_hiring: "289+" },
    { vacancy: "Cloud Services", active_hiring: "812+" },
    { vacancy: "Government", active_hiring: "1.3K+" },
    { vacancy: "Automotive", active_hiring: "512+" },
    { vacancy: "Agritech", active_hiring: "98+" },
    { vacancy: "Retail", active_hiring: "734+" },
    { vacancy: "Logistics", active_hiring: "436+" },
    { vacancy: "Hospitality", active_hiring: "378+" },
    { vacancy: "Telecom", active_hiring: "947+" },
    { vacancy: "Media", active_hiring: "219+" },
    { vacancy: "E-commerce", active_hiring: "1.2K+" },
    { vacancy: "Pharma", active_hiring: "643+" },
    { vacancy: "Gaming", active_hiring: "139+" },
    { vacancy: "SaaS", active_hiring: "2.3K+" },
    { vacancy: "Digital Marketing", active_hiring: "589+" },
    { vacancy: "Consulting", active_hiring: "1.1K+" },
    { vacancy: "Legal", active_hiring: "177+" },
    { vacancy: "Insurance", active_hiring: "733+" },
    { vacancy: "Construction", active_hiring: "388+" },
    { vacancy: "Education", active_hiring: "854+" },
    { vacancy: "FoodTech", active_hiring: "204+" },
    { vacancy: "Fashion", active_hiring: "167+" },
    { vacancy: "SpaceTech", active_hiring: "54+" },
    { vacancy: "Robotics", active_hiring: "92+" },
    { vacancy: "Travel", active_hiring: "478+" },
    { vacancy: "Freelance", active_hiring: "318+" },
    { vacancy: "Non-Profit", active_hiring: "88+" },
    { vacancy: "Real Estate", active_hiring: "661+" },
    { vacancy: "Startups", active_hiring: "3.2K+" },
    { vacancy: "Energy", active_hiring: "509+" },
    { vacancy: "Mining", active_hiring: "69+" },
    { vacancy: "Aerospace", active_hiring: "113+" },
    { vacancy: "VR/AR", active_hiring: "148+" },
    { vacancy: "Electronics", active_hiring: "392+" },
    { vacancy: "Textile", active_hiring: "231+" },
    { vacancy: "Publishing", active_hiring: "142+" },
    { vacancy: "Event Management", active_hiring: "219+" },
    { vacancy: "Music", active_hiring: "97+" },
    { vacancy: "Biotech", active_hiring: "271+" },
    { vacancy: "Data Analytics", active_hiring: "1.7K+" },
    { vacancy: "Human Resources", active_hiring: "427+" },
    { vacancy: "Customer Support", active_hiring: "563+" }
];

export default hiring.slice(0,6);