const jobData = [
  {
    jobRole: "Intern CTM",
    company: "Phonepe",
    star: "4.3",
    reviews: "152",
    experience: "0-1 Yrs",
    salary: "Not disclosed",
    location: "Bengaluru",
    posted: "1 day ago",
  },
  {
    jobRole: "Software Engineer Intern",
    company: "Google",
    star: "4.6",
    reviews: "322",
    experience: "0-1 Yrs",
    salary: "₹40,000/month",
    location: "Hyderabad",
    posted: "2 days ago",
  },
  {
    jobRole: "Data Analyst Intern",
    company: "TCS",
    star: "3.9",
    reviews: "204",
    experience: "0-1 Yrs",
    salary: "Not disclosed",
    location: "Mumbai",
    posted: "3 days ago",
  },
  {
    jobRole: "Backend Intern",
    company: "Zomato",
    star: "4.1",
    reviews: "187",
    experience: "0-1 Yrs",
    salary: "₹25,000/month",
    location: "Gurgaon",
    posted: "5 hours ago",
  },
  {
    jobRole: "Frontend Developer Intern",
    company: "Amazon",
    star: "4.4",
    reviews: "310",
    experience: "0-1 Yrs",
    salary: "₹35,000/month",
    location: "Chennai",
    posted: "4 days ago",
  },
  {
    jobRole: "Machine Learning Intern",
    company: "Flipkart",
    star: "4.2",
    reviews: "241",
    experience: "0-1 Yrs",
    salary: "₹30,000/month",
    location: "Bengaluru",
    posted: "1 day ago",
  },
  {
    jobRole: "SDE Intern",
    company: "Infosys",
    star: "3.8",
    reviews: "198",
    experience: "0-1 Yrs",
    salary: "₹20,000/month",
    location: "Pune",
    posted: "3 days ago",
  },
  {
    jobRole: "Data Science Intern",
    company: "Swiggy",
    star: "4.0",
    reviews: "175",
    experience: "0-1 Yrs",
    salary: "₹28,000/month",
    location: "Bengaluru",
    posted: "5 days ago",
  },
  {
    jobRole: "Business Analyst Intern",
    company: "Ola",
    star: "4.1",
    reviews: "160",
    experience: "0-1 Yrs",
    salary: "₹22,000/month",
    location: "Mumbai",
    posted: "2 days ago",
  },
  {
    jobRole: "Product Intern",
    company: "CRED",
    star: "4.5",
    reviews: "233",
    experience: "0-1 Yrs",
    salary: "₹50,000/month",
    location: "Remote",
    posted: "6 hours ago",
  },
  {
    jobRole: "DevOps Intern",
    company: "Paytm",
    star: "4.0",
    reviews: "142",
    experience: "0-1 Yrs",
    salary: "₹27,000/month",
    location: "Noida",
    posted: "1 day ago",
  },
  {
    jobRole: "UI/UX Intern",
    company: "Razorpay",
    star: "4.3",
    reviews: "198",
    experience: "0-1 Yrs",
    salary: "₹32,000/month",
    location: "Bengaluru",
    posted: "3 days ago",
  },
  {
    jobRole: "QA Intern",
    company: "Freshworks",
    star: "4.1",
    reviews: "162",
    experience: "0-1 Yrs",
    salary: "₹23,000/month",
    location: "Chennai",
    posted: "4 days ago",
  },
  {
    jobRole: "Android Developer Intern",
    company: "Samsung R&D",
    star: "4.2",
    reviews: "201",
    experience: "0-1 Yrs",
    salary: "₹34,000/month",
    location: "Noida",
    posted: "2 days ago",
  },
  {
    jobRole: "Cloud Intern",
    company: "Microsoft",
    star: "4.6",
    reviews: "318",
    experience: "0-1 Yrs",
    salary: "₹45,000/month",
    location: "Hyderabad",
    posted: "1 day ago",
  },
  {
    jobRole: "Blockchain Intern",
    company: "Polygon Labs",
    star: "4.4",
    reviews: "139",
    experience: "0-1 Yrs",
    salary: "₹55,000/month",
    location: "Remote",
    posted: "6 hours ago",
  },
  {
    jobRole: "Cybersecurity Intern",
    company: "Cisco",
    star: "4.5",
    reviews: "266",
    experience: "0-1 Yrs",
    salary: "₹42,000/month",
    location: "Bengaluru",
    posted: "2 days ago",
  },
  {
    jobRole: "Marketing Intern",
    company: "Meesho",
    star: "4.0",
    reviews: "120",
    experience: "0-1 Yrs",
    salary: "Not disclosed",
    location: "Bengaluru",
    posted: "1 day ago",
  },
  {
    jobRole: "Operations Intern",
    company: "Urban Company",
    star: "3.9",
    reviews: "143",
    experience: "0-1 Yrs",
    salary: "₹20,000/month",
    location: "Gurgaon",
    posted: "2 days ago",
  },
  {
    jobRole: "Content Writer Intern",
    company: "Unacademy",
    star: "4.1",
    reviews: "114",
    experience: "0-1 Yrs",
    salary: "₹18,000/month",
    location: "Remote",
    posted: "4 days ago",
  },
  {
    jobRole: "iOS Developer Intern",
    company: "BYJU’S",
    star: "3.7",
    reviews: "210",
    experience: "0-1 Yrs",
    salary: "₹25,000/month",
    location: "Bengaluru",
    posted: "3 days ago",
  },
  {
    jobRole: "Support Engineer Intern",
    company: "Zoho",
    star: "4.0",
    reviews: "178",
    experience: "0-1 Yrs",
    salary: "₹22,000/month",
    location: "Chennai",
    posted: "5 days ago",
  },
  {
    jobRole: "IT Support Intern",
    company: "Dell",
    star: "4.2",
    reviews: "223",
    experience: "0-1 Yrs",
    salary: "₹24,000/month",
    location: "Hyderabad",
    posted: "1 day ago",
  },
  {
    jobRole: "Game Developer Intern",
    company: "Nazara Tech",
    star: "4.0",
    reviews: "97",
    experience: "0-1 Yrs",
    salary: "₹30,000/month",
    location: "Mumbai",
    posted: "2 days ago",
  },
  {
    jobRole: "Research Intern",
    company: "ISRO",
    star: "4.5",
    reviews: "276",
    experience: "0-1 Yrs",
    salary: "Not disclosed",
    location: "Bengaluru",
    posted: "1 day ago",
  },
  {
    jobRole: "Design Intern",
    company: "Adobe",
    star: "4.4",
    reviews: "188",
    experience: "0-1 Yrs",
    salary: "₹36,000/month",
    location: "Noida",
    posted: "2 days ago",
  },
  {
    jobRole: "Systems Intern",
    company: "HCL",
    star: "3.8",
    reviews: "199",
    experience: "0-1 Yrs",
    salary: "₹19,000/month",
    location: "Chennai",
    posted: "5 days ago",
  },
  {
    jobRole: "AR/VR Intern",
    company: "Tata Elxsi",
    star: "4.1",
    reviews: "156",
    experience: "0-1 Yrs",
    salary: "₹29,000/month",
    location: "Bengaluru",
    posted: "4 days ago",
  },
  {
    jobRole: "Full Stack Intern",
    company: "Mindtree",
    star: "3.9",
    reviews: "170",
    experience: "0-1 Yrs",
    salary: "₹26,000/month",
    location: "Hyderabad",
    posted: "1 day ago",
  },
  {
    jobRole: "Technical Writer Intern",
    company: "Atlassian",
    star: "4.6",
    reviews: "215",
    experience: "0-1 Yrs",
    salary: "₹33,000/month",
    location: "Remote",
    posted: "7 hours ago",
  },
  {
    jobRole: "NLP Intern",
    company: "Jio Platforms",
    star: "4.0",
    reviews: "147",
    experience: "0-1 Yrs",
    salary: "₹28,000/month",
    location: "Mumbai",
    posted: "2 days ago",
  },
      {
    jobRole: "Video Editing Intern",
    company: "MX Player",
    star: "3.9",
    reviews: "132",
    experience: "0-1 Yrs",
    salary: "₹20,000/month",
    location: "Mumbai",
    posted: "2 days ago",
  },
  {
    jobRole: "Finance Intern",
    company: "ICICI Bank",
    star: "4.0",
    reviews: "178",
    experience: "0-1 Yrs",
    salary: "₹18,000/month",
    location: "Chennai",
    posted: "4 days ago",
  },
  {
    jobRole: "HR Intern",
    company: "Wipro",
    star: "3.8",
    reviews: "154",
    experience: "0-1 Yrs",
    salary: "₹17,000/month",
    location: "Bengaluru",
    posted: "3 days ago",
  },
  {
    jobRole: "Legal Intern",
    company: "L&T",
    star: "4.2",
    reviews: "144",
    experience: "0-1 Yrs",
    salary: "Not disclosed",
    location: "Mumbai",
    posted: "5 days ago",
  },
  {
    jobRole: "AI Research Intern",
    company: "OpenAI India",
    star: "4.8",
    reviews: "312",
    experience: "0-1 Yrs",
    salary: "₹60,000/month",
    location: "Remote",
    posted: "1 day ago",
  },
  {
    jobRole: "Game Tester Intern",
    company: "Ubisoft India",
    star: "4.0",
    reviews: "123",
    experience: "0-1 Yrs",
    salary: "₹22,000/month",
    location: "Pune",
    posted: "6 hours ago",
  },
  {
    jobRole: "Sales Intern",
    company: "Reliance Retail",
    star: "3.9",
    reviews: "141",
    experience: "0-1 Yrs",
    salary: "₹15,000/month",
    location: "Ahmedabad",
    posted: "2 days ago",
  },
  {
    jobRole: "Customer Support Intern",
    company: "AirAsia",
    star: "4.1",
    reviews: "128",
    experience: "0-1 Yrs",
    salary: "₹18,000/month",
    location: "Delhi",
    posted: "3 days ago",
  },
  {
    jobRole: "Electronics Intern",
    company: "Qualcomm",
    star: "4.5",
    reviews: "219",
    experience: "0-1 Yrs",
    salary: "₹35,000/month",
    location: "Hyderabad",
    posted: "1 day ago",
  },
  {
    jobRole: "Physics Research Intern",
    company: "IIT Bombay",
    star: "4.7",
    reviews: "289",
    experience: "0-1 Yrs",
    salary: "₹20,000/month",
    location: "Mumbai",
    posted: "2 days ago",
  },
  {
    jobRole: "Python Developer Intern",
    company: "Scaler",
    star: "4.4",
    reviews: "193",
    experience: "0-1 Yrs",
    salary: "₹30,000/month",
    location: "Remote",
    posted: "6 hours ago",
  },
  {
    jobRole: "Full Stack Intern",
    company: "Pepcoding",
    star: "4.0",
    reviews: "114",
    experience: "0-1 Yrs",
    salary: "₹25,000/month",
    location: "Delhi",
    posted: "1 day ago",
  },
  {
    jobRole: "Graphics Designer Intern",
    company: "Canva India",
    star: "4.3",
    reviews: "178",
    experience: "0-1 Yrs",
    salary: "₹26,000/month",
    location: "Remote",
    posted: "2 days ago",
  },
  {
    jobRole: "Digital Marketing Intern",
    company: "WhiteHat Jr",
    star: "3.8",
    reviews: "102",
    experience: "0-1 Yrs",
    salary: "₹20,000/month",
    location: "Mumbai",
    posted: "3 days ago",
  },
  {
    jobRole: "Technical Recruiter Intern",
    company: "Tech Mahindra",
    star: "3.9",
    reviews: "158",
    experience: "0-1 Yrs",
    salary: "₹19,000/month",
    location: "Hyderabad",
    posted: "4 days ago",
  },
  {
    jobRole: "Robotics Intern",
    company: "ABB",
    star: "4.2",
    reviews: "173",
    experience: "0-1 Yrs",
    salary: "₹40,000/month",
    location: "Bengaluru",
    posted: "2 days ago",
  },
  {
    jobRole: "Systems Intern",
    company: "Bosch",
    star: "4.0",
    reviews: "192",
    experience: "0-1 Yrs",
    salary: "₹27,000/month",
    location: "Coimbatore",
    posted: "1 day ago",
  },
  {
    jobRole: "Energy Research Intern",
    company: "NTPC",
    star: "3.9",
    reviews: "149",
    experience: "0-1 Yrs",
    salary: "₹21,000/month",
    location: "Delhi",
    posted: "2 days ago",
  },
  {
    jobRole: "Healthcare Data Intern",
    company: "Apollo Hospitals",
    star: "4.1",
    reviews: "170",
    experience: "0-1 Yrs",
    salary: "₹22,000/month",
    location: "Chennai",
    posted: "1 day ago",
  },
  {
    jobRole: "GIS Intern",
    company: "Esri India",
    star: "4.2",
    reviews: "127",
    experience: "0-1 Yrs",
    salary: "₹25,000/month",
    location: "Noida",
    posted: "3 days ago",
  }
  
];


export default jobData;


// export const fetchJobData = () => {
//       return new Promise((resolve) => {
//         setTimeout(() => {
//           resolve(jobData);
//         },1000);
//       });
// };